version: "3.8"

services:
  traefik:
    image: "traefik"
    command:
      - "--global.sendAnonymousUsage=false"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8080"
      - "--log.level=WARN"
    labels:
      - "traefik.http.routers.http_catchall.entrypoints=web"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nbaq:
    image: "nbaq"
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.nbaq.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.nbaq.rule=Host(`api.localhost`)"
      - "traefik.http.routers.nbaq.entrypoints=web"
    secrets:
      - blob_secret
    depends_on:
      - "minio"
  nbac:
    image: "nbac"
    volumes:
      - "./conf:/usr/local/nbac/conf"
    secrets:
      - blob_secret
    depends_on:
      - "minio"
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${NBALAKE_KEY}
      - MINIO_ROOT_PASSWORD=${NBALAKE_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minioconsole.service=minioconsole"
      - "traefik.http.routers.minioconsole.rule=Host(`nbalake.localhost`)"
      #- "traefik.http.routers.minioconsole.rule=PathPrefix(`/nbalake`)"
      - "traefik.http.routers.minioconsole.entrypoints=web"
      - "traefik.http.services.minioconsole.loadbalancer.server.port=9001"
    volumes:
      - data:/data

secrets:
  blob_secret:
    file: ./conf/config.json
volumes:
  data:
  conf:
